language: php
dist: focal

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

env:
  - WP_VERSION=latest

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.4
      env: WP_VERSION=latest RUN_PHPCS=1

before_install:
  - phpenv config-rm xdebug.ini || true

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs --colors -p -s -v -n --standard=.phpcs.xml .